# -*- coding: utf-8 -*-
"""Predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mMZn7yfNX1AA3hnxzG4sMW2dJW9GIv7P
"""

import pandas as pd
import numpy as np
import joblib

model = joblib.load('/content/xgb_spending_predictor.pkl')
user_segments = joblib.load('/content/user_segments.pkl')
low_error_users = user_segments['low_error_users']
high_error_users = user_segments['high_error_users']

def predict_spending(user_id, latest_spending, rolling3_spending, target_month,
                    is_ramadan=0, is_lebaran=0, is_akhir_tahun=0):
    """Fungsi prediksi untuk digunakan dalam web app"""

    # Buat data input
    input_data = pd.DataFrame({
        'pengeluaran_bulan_lalu': [latest_spending],
        'rolling3_pengeluaran': [rolling3_spending],
        'bulan': [target_month],
        'is_ramadan': [is_ramadan],
        'is_lebaran': [is_lebaran],
        'is_akhir_tahun': [is_akhir_tahun]
    })

    # Prediksi
    pred_log = model.predict(input_data)[0]
    prediction = np.expm1(pred_log)

    # Buat rentang prediksi berdasarkan segmen user
    if user_id in high_error_users:
        confidence = "low"
        lower = prediction * 0.4  # -60%
        upper = prediction * 2.0  # +100%
    elif user_id in low_error_users:
        confidence = "high"
        lower = prediction * 0.8  # -20%
        upper = prediction * 1.2  # +20%
    else:
        confidence = "medium"
        lower = prediction * 0.6  # -40%
        upper = prediction * 1.4  # +40%

    # Format hasil untuk web
    return {
        'user_id': user_id,
        'prediction': int(prediction),
        'min_prediction': int(lower),
        'max_prediction': int(upper),
        'confidence_level': confidence
    }